language: node_js
node_js:
  - 10.18.1
cache:
  directories:
    - node_modules
script:
  - yarn run doc
  - yarn run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # github 上的token环境变量
  local-dir: dist ## 根据情况自定义到静态文件输出目录
  target-branch: gh-pages
  verbose: true
  email: 1245036094@qq.com
  name: xing.he
  keep_history: true # 默认是 --force 模式，这里保留记录
  # commit_message: Deploy %{project_name} to %{target_branch} on Travis # 没有用啊！！！
  on:
    branch: master
